config/routes.rb
GradDevProject::Application.routes.draw do
  devise_for :admins

  

  resources :quizzes do
    resources :attempts, only: [:new, :create, :show]
    resources :questions do
      resources :answers
    end
  end
  root :to => "quizzes#index"

  match '/delete_quiz', to: 'quizzes#destroy', via: 'delete'

   
   

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base

	belongs_to :question

  # validates :question_id, presence: true
  validates :response, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :quiz
  has_many :answers

	validates :query, presence: true

	accepts_nested_attributes_for :answers, reject_if: ->(a) { a[:response].blank? }

  def populate_answers(number_of_answers)
    number_of_answers.times { answers.build }
  end

  def correct_answer
    answers.find_by_correctness(true)
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :questions
  accepts_nested_attributes_for :questions, reject_if: ->(q) { q[:query].blank? }
	validates :title, presence: true


  def populate(number_of_questions: 0, number_of_answers: 0)
   
    number_of_questions.times do
      question = questions.build
      question.populate_answers(number_of_answers)
    end
  end

  def correct_answer_ids
    questions.map { |q| q.correct_answer.id }
  end

end

app/models/scorer.rb
class Scorer
  def initialize(quiz)
    @quiz = quiz
  end

  def total(answer_ids)
    correct_num = (@quiz.correct_answer_ids & answer_ids.map(&:to_i)).length
    ((correct_num/answer_ids.length.to_f) * 100).ceil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attemps_controller.rb
class AttemptsController < ApplicationController

  def new
    @quiz = Quiz.find params[:quiz_id]
  end

  def create
    @quiz = Quiz.find params[:quiz_id]
    answer_ids = params[:answer_ids].values
    scorer = Scorer.new(@quiz)

    final_score = scorer.total(answer_ids)
    render text: "#{final_score}%"
  end

end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  def new
    @quiz = Quiz.find params[:quiz_id]
  end

  def create
    @quiz = Quiz.find params[:quiz_id]
    answer_ids = params[:answer_ids].values
    scorer = Scorer.new(@quiz)
    final_score = scorer.total(answer_ids)
    render text: "#{final_score}%"
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def new
    @quiz = Quiz.new
    @quiz.populate(number_of_questions: 5, number_of_answers: 4)
  end

  def create
    @quiz = Quiz.new quiz_params

    if @quiz.save
      redirect_to @quiz
    else
      render 'new'
    end
  end

  def edit
    @quiz = Quiz.find params[:id]
  end

  def update
    @quiz = Quiz.find params[:id]
    if @quiz.update quiz_params
      redirect_to @quiz
    else
      render 'edit'
    end
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy
    redirect_to root_path
  end

  private

  def quiz_params
    params.require(:quiz)
          .permit :title, questions_attributes: 
                            [:id, :query, answers_attributes: 
                                [:id, :response, :correctness]]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attempts/create.html.erb
<h1>Attempts#create</h1>
<p>Find me in app/views/attempts/create.html.erb</p>

app/views/attempts/new.html.erb
<%= form_tag quiz_attempts_path do %>

  <% @quiz.questions.each do |question| %>

    <h4><%= question.query %></h4>

    <% question.answers.each do |answer| %>
      <label>
        <%= answer.response %>
        <%= radio_button_tag "answer_ids[#{question.id}]", answer.id %>
      </label>
    <% end %>

  <% end %>

  <%= submit_tag "Submit" %>

<% end %>

app/views/layouts/_nav.html.erb
<% if admin_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_admin_session_path)  %>  
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GradDevProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/nav' %>
<%= yield %>

</body>
</html>

app/views/quizzes/_answer_fields.html.erb
<br><%= f.fields_for :answers do |answer_f| %>
  <%= answer_f.label :response, 'Answer' %>
  <%= answer_f.text_field :response %>
  <%= answer_f.label :correctness, 'Correct?' %>
  <%= answer_f.check_box :correctness %><br>
<% end %>

app/views/quizzes/_question_fields.html.erb
<% n = 1 %>
<%= f.fields_for :questions do |question_f| %>
  
  <fieldset id="question_<%= n %>">

    <%= question_f.label :query, "Question #{n}" %>

    <%= question_f.text_field :query %>

    <%= render 'answer_fields', f: question_f %>
    <% n += 1 %>
  </fieldset>

<% end %> 

app/views/quizzes/edit.html.erb
<% if @quiz.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
      <% @quiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @quiz do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Your title here' %>
  <%= render 'question_fields', f: f %>
  
  <%= f.submit %>

<% end %>

app/views/quizzes/index.html.erb
<% @quizzes.each do |quiz| %>
  <h3><%= link_to quiz.title, quiz_path(quiz) %></h3>
  <%= link_to "Delete Quiz", delete_quiz_path(id: quiz.id), method: :delete %>
  <%= link_to "Edit Quiz", edit_quiz_path(id: quiz.id) %>
<% end %>

<% if @quizzes.empty? %>
  <h3>No quizzes yet</h3>
  <%= link_to "Create one", new_quiz_path %>
<% else %>
  <%= link_to "Create a quiz", new_quiz_path %>
<% end %>

app/views/quizzes/new.html.erb
<% if @quiz.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @quiz.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @quiz do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Your title here' %>
  
  <%= render 'question_fields', f: f %>

  <%= f.submit %>

<% end %>

app/views/quizzes/show.html.erb
<h1><%= @quiz.title %></h1>

<%= link_to "Play quiz", new_quiz_attempt_path(@quiz)%>

<% @quiz.questions.each do |question| %>
  <%= question.query %>
  <% question.answers.each do |answer| %>
    <%= answer.response %>
  <% end %>
<% end %>